### ISSUE TITLE
pde file type conflict

### ISSUE THREAD

**Issue by sophacles** [sophacles/vim-processing#29]
There have been a few tickets recently - #24 and #27, which have issues resulting from arduino using the `.pde` file extension as well as processing. @crazymaster has a possible solution in #28.

Newer versions of arduino use the `.ino` extension instead of `.pde` - probably because of this. 

Unfortunately processing is a dialect of java, and the arduino language is a dialect of C++, meaning we can't usefully just use either. (Not to mention the backend toolchains are completely different).

This ticket is for discussion of the issue. So far some thoughts and ideas have floated around the tickets mentioned above:

* override pde default to ensure processing
   * **pros:**
       * this is a simple solution
   * **cons:**
       * this is it is a bit "not playing nice".
       * it still is effectively runtime ordering based

* contact other vim plugin writers, as well as vim_dev mailing list.
   * **pros:**
       * this is playing nice
       * will maybe come up with a better, workable solution
       * allows for proper backwards compatibility for arduino `.pde` when needed
   * **cons**
      * not a fast soution
      * may result in way too much bikeshedding

Some other thoughts I have:

* is there a way to definitively identify a processing project vs an arduino project?
   * once source is actually present, probably
   * also, perhaps it can be found from the file path

* is there a lot of overlap between people doing arduino and processing? I know I count, do others?

* am I making this too hard?

* Whatever the decision is, there should be a note in the readme and the documentation about this issue.

Anyone with input, please discuss below. I figure we should take a little time to hash this out properly before committing to a course of action to reduce the odds of having to revisit this again and again.

**Comment by edne** [comment]
ping @sophacles 
the plugin is broken. Please, merge the @crazymaster pull-request

**Comment by sophacles** [comment]
#28 is merged. I'm still a bit wary of just stepping on the Arduino file toes... But maybe I'm of a rare type that actually uses both Arduino and Processing. Still half-thinking of a better fix.

**Comment by sophacles** [comment]
Catching up on older things, I'm closing this ticket since my recent adventures in Arduino land are showing no conflicts - I think the @crazymaster fix is the correct behavior

**Comment by dvzrv** [comment]
Hmm, I'm having the same issues with this plugin: https://github.com/stevearc/vim-arduino/
It continuesly activates arduino, but not processing for *.pde files, even if I remove the *.pde settings in the vim-arduino ftdetect and ftplugin scripts.
Removing the plugin from being loaded resolves the issue...
Can anyone reproduce this? oO

**Comment by crazymaster** [comment]
> Hmm, I'm having the same issues with this plugin: https://github.com/stevearc/vim-arduino/
> It continuesly activates arduino, but not processing for *.pde files, even if I remove the *.pde settings in the vim-arduino ftdetect and ftplugin scripts.
> Removing the plugin from being loaded resolves the issue...
> Can anyone reproduce this? oO

This patch **for stevearc/vim-arduino** will solve the issue with that plugin.
```diff
diff --git a/ftdetect/arduino.vim b/ftdetect/arduino.vim
index 048c616..deb92f4 100644
--- a/ftdetect/arduino.vim
+++ b/ftdetect/arduino.vim
@@ -1 +1 @@
-au BufRead,BufNewFile *.ino,*.pde setlocal ft=arduino
+au BufRead,BufNewFile *.ino,*.pde setf=arduino
```

cf. `:h :setf`
