### ISSUE TITLE
No such highlight group name: javaError2

### ISSUE THREAD

**Issue by qSeven** [sophacles/vim-processing#34]
Hello,  When I load .pde's I get the following error:

Error detected while processing /home/USER/.vim/bundle/vim-processsing/syntax/processing.vim
line 11:
E28: No such highlight group name: javaError2

Afterwords, 
*the make command looks for a make file in my directory
*K looks for linux man pages
*RunProcessing command isn't available
*g:processing_doc_style isn't showing up in command auto complete
*help processing-intro loads
*syntax highlighting is present though
 
I installed using Vundle, processing-java is in my PATH. 

I couldn't find anything I have done wrong based on documentation but I might have missed something.  Sorry if this is the wrong place for this but thanks for the help

**Comment by crazymaster** [comment]
Do you use other java syntax plugin?

**Comment by qSeven** [comment]
I have syntastics and neocomplete, also installed with vundle.  When I comment them out in my vimrc(which disables them as far as I can tell and is said to in the vundle documentation) I still get the same errors.

**Comment by crazymaster** [comment]
Can you open .java file correctly? Because syntax/processing.vim loads syntax/java.vim.

And it will help to include information about the version of Vim.
You can get the information with this command:
`:so $VIMRUNTIME/bugreport.vim`

**Comment by qSeven** [comment]
I can open .java with no errors,I can use the snippits from neocomplete and there is syntax highlighting.

[bugreport pastebin](http://pastebin.com/qNjvamp8)

**Comment by crazymaster** [comment]
You seem to load syntax/processing.vim twice.
~/.vim/syntax/processing.vim
~/.vim/bundle/vim-processing/syntax/processing.vim

However, it have a problem with include guard, so I will fix it.

**Comment by sophacles** [comment]
@qSeven I just merged @crazymaster 's patch - this should fix your issue. Please update your bundle (or whichever method of vim plugin-fu you are using :) ) to the latest from github and let us know if there are further problems.

**Comment by qSeven** [comment]
Excelent! that worked.

**Comment by sophacles** [comment]
Good news! Closing as fixed.
