### ISSUE TITLE
Can't open reference manual (K)

### ISSUE THREAD

**Issue by cameyo42** [sophacles/vim-processing#38]
I have installed this repository on mac and win7. All works fine.
On win10 i got the following error when pressing 'K' on a processing keyword:
**Error detected while processing function ProcessingDoc[26]..processing#docopen:**
**line    5:**
**E887: Sorry, this command is disabled, the Python's site module could not be loaded.**
I have python 2.7.11.
Can you help me ?
Thanks

p.s. **F5** works well

**Comment by crazymaster** [comment]
This is **not** plugin's bug.

>https://tuxproject.de/projects/vim/
Python 2.7.11 requires you to rename a registry key when using the x86 builds. 

>https://github.com/k-takata/vim/commit/435be6dc61347d92029768f1678fdfdb9a543005

Can you try workaround?
```
reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:32
reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:64
```

**Comment by cameyo42** [comment]
Works perfectly.
Very Thanks.
